### ISSUE TITLE
Modularize plugin not merging custom.appSync.dataSources correctly  

### ISSUE THREAD

**Issue by Shereef** [icarus-sullivan/serverless-plugin-modularize#17]
Modularize plugin not merging custom.appSync.dataSources correctly similarly custom.appSync.mappingTemplates
<img width="467" alt="image" src="https://user-images.githubusercontent.com/356763/153964489-04820c42-5fbf-45e0-9f43-3c80a57838d9.png">

I had to uninstall modularize today because it wasn't merging those correctly

Only one of those would be present in the serverless.json and the rest weren't there

**Comment by Shereef** [comment]
@icarus-sullivan Please help me fix this as I don't like the size of my serverless.yml

Where would I start looking ?

**Comment by icarus-sullivan** [comment]
So you only saw 1 of the array items??

**Comment by rafapaulin** [comment]
yes @icarus-sullivan... just one item shows up. I have stumbled on the same problem.

**Comment by rafapaulin** [comment]
![image](https://user-images.githubusercontent.com/13452406/186012270-7fa5320f-f988-45ed-836d-4081ff6ed856.png)
![image](https://user-images.githubusercontent.com/13452406/186012289-b1b1e160-d8cd-40f6-b673-ff2c3b8f9695.png)
![image](https://user-images.githubusercontent.com/13452406/186012314-3aa317f5-0e38-42c1-8bf2-bfb2ada0fbfd.png)

then, I got this for appsync, when run the `merged` command
![image](https://user-images.githubusercontent.com/13452406/186012421-7306ea12-858f-46c2-8b55-c29bdc1f8391.png)

**Comment by icarus-sullivan** [comment]
So ... I've been working on this off and on the last couple weeks. I have a workable version I can deploy to fix this. However while researching some stuff I stumbled across this ... https://www.serverless.com/framework/docs/guides/compose

This effectively makes my plugin obsolete, however I can publish my changes soon to hopefully help folks on pre serverless 3.15

**Comment by icarus-sullivan** [comment]
I've published version 3.0.0, it didn't change the api but I figured it was a substantial enough change to do a major version. Please let me know if this works for you folks and I'll close the issue out.

**Comment by brettstack** [comment]
I don't think Serverless Compose makes your plugin obsolete since it deploys them as individual services/stacks.
